EXPERIMENT:
  NAME: "Baseline, cifar100, resnet32x4 teacher, resnet8x4 student."
  TAG: "kd,resnet32x4,resnet8x4"
  PROJECT: "disagreement_augmentation"
DISTILLER:
  TYPE: "KD"
  TEACHER: "resnet32x4"
  STUDENT: "resnet8x4"
LOG:
  WANDB: True
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"