EXPERIMENT:
  NAME: "Disagreement Augmented, cifar100, vgg13 teacher, vgg8 student, using gt labels."
  TAG: "kd,vgg13,vgg8"
  PROJECT: "disagreement_augmentation"
DISTILLER:
  TYPE: "DA"
  TEACHER: "vgg13"
  STUDENT: "vgg8"
LOG:
  WANDB: True
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
DA:
  LR: 0.01778
  EPOCHS: 1
  PROB: 0.7374
