EXPERIMENT:
  NAME: "DA, tiny_imagenet, resnet34 teacher, MobileNetV2 student."
  TAG: "kd,resnet34,MobileNetV2"
  PROJECT: "disagreement_augmentation"
DATASET:
  TYPE: "tiny_imagenet"
DISTILLER:
  TYPE: "DA"
  TEACHER: "resnet34"
  STUDENT: "MobileNetV2"
LOG:
  WANDB: True
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
DA:
  LR: 0.01778
  EPOCHS: 1
  PROB: 0.7374