EXPERIMENT:
  NAME: "KD + logit stand, resnet32x4/resnet8x4, cifar100"
  TAG: "kd,resnet32x4,resnet8x4"
  PROJECT: "logit_stand"
  LOGIT_STAND: True
DISTILLER:
  TYPE: "KD"
  TEACHER: "resnet32x4"
  STUDENT: "resnet8x4"
LOG:
  WANDB: True
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"