EXPERIMENT:
  NAME: "Teacher fine tuning, ResNet18"
  TAG: "teacher fine tuning,ResNet18"
  PROJECT: "tiny_imagenet200"
DATASET:
  TYPE: "tiny_imagenet"
DISTILLER:
  TYPE: "NONE"
  STUDENT: "ResNet18"
LOG:
  WANDB: False
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 20
  LR: 0.01
  LR_DECAY_STAGES: [5, 5, 5]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"