EXPERIMENT:
  NAME: "Teacher fine tuning, resnet34"
  TAG: "teacher fine tuning,resnet34"
  PROJECT: "tiny_imagenet200"
DATASET:
  TYPE: "tiny_imagenet"
DISTILLER:
  TYPE: "NONE"
  STUDENT: "resnet34"
LOG:
  WANDB: True
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 40
  LR: 0.01
  LR_DECAY_STAGES: [10, 20, 30]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"